spring:
  datasource:
    url: jdbc:mysql://localhost:33061/mysql
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
